# Generated by Django 2.0 on 2018-02-10 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episode',
            name='published_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
