# Generated by Django 2.0 on 2018-02-05 11:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collections',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('episode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feed.Episode')),
                ('mst_collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feed.MstCollection')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='collection',
            name='channel',
        ),
        migrations.RemoveField(
            model_name='collection',
            name='mst_collection',
        ),
        migrations.DeleteModel(
            name='Collection',
        ),
    ]
