# Generated by Django 2.0 on 2017-12-27 21:44

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('feed', '0002_auto_20171226_2204'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Star',
            new_name='Like',
        ),
    ]
