# Generated by Django 2.0 on 2018-01-20 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0002_auto_20180120_1953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='cover_image',
            field=models.ImageField(blank=True, height_field='200', null=True, upload_to='images/', width_field='200'),
        ),
    ]
