# Generated by Django 2.0 on 2018-02-17 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0002_auto_20180217_2114'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='height_field',
            field=models.IntegerField(default=400),
        ),
        migrations.AddField(
            model_name='channel',
            name='width_field',
            field=models.IntegerField(default=400),
        ),
    ]
