# Generated by Django 2.0 on 2018-01-02 16:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0006_auto_20171230_1152'),
    ]

    operations = [
        migrations.CreateModel(
            name='Channels',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('code', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('link', models.URLField()),
                ('author_name', models.CharField(max_length=100)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('is_active', models.BooleanField(default=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='feed.Category')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='channel',
            name='category',
        ),
        migrations.RenameField(
            model_name='episode',
            old_name='summary',
            new_name='description',
        ),
        migrations.AlterField(
            model_name='episode',
            name='channel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='feed.Channels'),
        ),
        migrations.AlterField(
            model_name='subscribe',
            name='channel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='feed.Channels'),
        ),
        migrations.DeleteModel(
            name='Channel',
        ),
    ]
