# Generated by Django 2.0 on 2018-01-06 10:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('feed', '0008_auto_20180102_1625'),
    ]

    operations = [
        migrations.CreateModel(
            name='Channels',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('link', models.URLField()),
                ('author_name', models.CharField(max_length=100)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('is_active', models.BooleanField(default=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='feed.Category')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Episodes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('link', models.URLField()),
                ('description', models.TextField(blank=True, null=True)),
                ('release_date', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='feed.Channels')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MstPlaylists',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=100)),
                ('is_public', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='channel',
            name='category',
        ),
        migrations.RemoveField(
            model_name='episode',
            name='channel',
        ),
        migrations.RemoveField(
            model_name='mstplaylist',
            name='user',
        ),
        migrations.AlterField(
            model_name='like',
            name='episode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feed.Episodes'),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='episode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feed.Episodes'),
        ),
        migrations.AlterField(
            model_name='subscribe',
            name='channel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='feed.Channels'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='episode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feed.Episodes'),
        ),
        migrations.DeleteModel(
            name='Channel',
        ),
        migrations.DeleteModel(
            name='Episode',
        ),
        migrations.DeleteModel(
            name='MstPlaylist',
        ),
    ]
