# Generated by Django 2.0 on 2018-01-06 10:05

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('feed', '0009_auto_20180106_1002'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Channels',
            new_name='Channel',
        ),
        migrations.RenameModel(
            old_name='Episodes',
            new_name='Episode',
        ),
        migrations.RenameModel(
            old_name='MstPlaylists',
            new_name='MstPlaylist',
        ),
    ]
