# Generated by Django 2.0 on 2018-01-06 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0011_auto_20180106_1016'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Channels',
            new_name='Channel',
        ),
    ]
