# Generated by Django 2.0 on 2018-01-07 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0012_auto_20180106_1017'),
    ]

    operations = [
        migrations.AddField(
            model_name='episode',
            name='duration',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
