# Generated by Django 2.0 on 2018-01-09 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0015_auto_20180109_2058'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Categories',
            new_name='Category',
        ),
    ]
