# Generated by Django 2.0 on 2018-01-14 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0017_auto_20180114_1814'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Playlists',
            new_name='Playlist',
        ),
        migrations.RenameModel(
            old_name='Tags',
            new_name='Tag',
        ),
    ]
