# Generated by Django 2.0 on 2018-01-16 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0018_auto_20180114_1815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='author_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
