# Generated by Django 2.0 on 2018-01-19 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0020_auto_20180119_1940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/', width_field='200'),
        ),
    ]
