# Generated by Django 2.0 on 2018-01-19 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0021_auto_20180119_1955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
